// Comprehensive Events Database - 2026-2027
// Last updated: March 9, 2026

const events = [
  // === 2026 Q1 EVENTS ===
  {
    id: 1,
    name: "World Economic Forum (Davos)",
    startDate: "2026-01-19",
    endDate: "2026-01-23",
    location: "Davos, Switzerland",
    region: "Europe",
    attendance: 3000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Policy/Regulatory", "Institutional Investors", "C-Suite Executives"],
    url: "https://www.weforum.org",
    notes: "World's most influential gathering of political and business leaders. Digital currency and blockchain increasingly featured. Critical for policy insights and networking with sovereigns, central bankers, and top-tier allocators.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 2,
    name: "Consensus Hong Kong",
    startDate: "2026-02-10",
    endDate: "2026-02-12",
    location: "Hong Kong",
    region: "Asia",
    attendance: 8000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Crypto Natives", "Hedge Funds", "Founders/Builders"],
    url: "https://consensus.coindesk.com",
    notes: "CoinDesk's Asia flagship. Critical gateway to Asian institutional capital and APAC crypto ecosystem. Strong regulatory and institutional finance focus.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 3,
    name: "ETHDenver",
    startDate: "2026-02-17",
    endDate: "2026-02-21",
    location: "Denver, CO",
    region: "North America",
    attendance: 15000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Founders/Builders", "Developers", "VCs", "Community"],
    url: "https://ethdenver.com",
    notes: "World's largest Ethereum community gathering. Strong builder/developer focus. BUIDLathon format. Essential for Ethereum ecosystem insights.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 4,
    name: "iConnections Global Alts",
    startDate: "2026-02-23",
    endDate: "2026-02-26",
    location: "Miami Beach, FL",
    region: "North America",
    attendance: 5000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Hedge Funds", "Allocators", "Family Offices"],
    url: "https://iconnections.io",
    notes: "World's largest cap intro event. Structured 1:1 meetings between allocators and managers. Crypto/digital assets increasingly represented. Critical for fundraising.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 5,
    name: "Digital Asset Forum (DAF) London",
    startDate: "2026-02-05",
    endDate: "2026-02-06",
    location: "London, UK",
    region: "Europe",
    attendance: 1500,
    category: "crossover",
    tier: 2,
    estimated: false,
    audience: ["Institutional Investors", "Asset Managers", "Policy/Regulatory"],
    url: "https://www.daf.london",
    notes: "Premier institutional digital assets conference in Europe. TradFi meets crypto. Strong regulatory and policy focus. Key European allocators present.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 6,
    name: "FIA Boca (International Futures Industry Conference)",
    startDate: "2026-03-08",
    endDate: "2026-03-11",
    location: "Boca Raton, FL",
    region: "North America",
    attendance: 2500,
    category: "institutional",
    tier: 2,
    estimated: false,
    audience: ["Institutional Investors", "Derivatives Traders", "Clearing Houses"],
    url: "https://www.fia.org",
    notes: "Global cleared derivatives industry's most significant gathering. Crypto derivatives increasingly featured. Critical for futures/options market structure.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 7,
    name: "DC Blockchain Summit",
    startDate: "2026-03-04",
    endDate: "2026-03-05",
    location: "Washington, DC",
    region: "North America",
    attendance: 2000,
    category: "crossover",
    tier: 2,
    estimated: false,
    audience: ["Policy/Regulatory", "Institutional Investors", "Industry Leaders"],
    url: "https://dcblockchainsummit.com",
    notes: "Policy-focused summit with regulators, policymakers, and industry leaders. Critical for understanding U.S. regulatory direction.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 8,
    name: "Digital Asset Summit NYC (Blockworks)",
    startDate: "2026-03-24",
    endDate: "2026-03-26",
    location: "New York, NY",
    region: "North America",
    attendance: 2500,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Crypto Natives", "Hedge Funds", "RWA Issuers"],
    url: "https://blockworks.co/event/digital-asset-summit-nyc-2026",
    notes: "Premier institutional crypto conference. Bridges TradFi and DeFi. Strong allocator attendance. Focus on institutional adoption, RWAs, and market structure.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 9,
    name: "EthCC (Ethereum Community Conference)",
    startDate: "2026-03-30",
    endDate: "2026-04-02",
    location: "Cannes, France",
    region: "Europe",
    attendance: 5000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Founders/Builders", "Developers", "Researchers", "VCs"],
    url: "https://ethcc.io",
    notes: "Largest annual European Ethereum event. Deep technical focus. Core developers and researchers present. Committed to Cannes through 2028.",
    digitalAssetRelevance: "Yes"
  },

  // === 2026 Q2 EVENTS ===
  {
    id: 10,
    name: "Paris Blockchain Week",
    startDate: "2026-04-15",
    endDate: "2026-04-16",
    location: "Paris, France",
    region: "Europe",
    attendance: 7000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Founders/Builders", "Policy/Regulatory"],
    url: "https://www.parisblockchainweek.com",
    notes: "Europe's leading institutional conference for digital assets and traditional finance convergence. Held at Carrousel du Louvre. Strong European allocator presence.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 11,
    name: "Bitcoin Conference (Las Vegas)",
    startDate: "2026-04-27",
    endDate: "2026-04-29",
    location: "Las Vegas, NV",
    region: "North America",
    attendance: 25000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Bitcoin Maximalists", "Institutional Investors", "Miners", "Policy"],
    url: "https://b.tc/conference",
    notes: "World's largest Bitcoin-specific conference. Strong institutional presence. Political and policy focus. Frequent major announcements.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 12,
    name: "TOKEN2049 Dubai",
    startDate: "2026-04-29",
    endDate: "2026-04-30",
    location: "Dubai, UAE",
    region: "Middle East",
    attendance: 15000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Founders/Builders", "VCs", "Exchanges"],
    url: "https://www.token2049.com/dubai",
    notes: "TOKEN2049's Middle East flagship (Week: Apr 27-May 3). Gateway to Middle Eastern capital. Strong institutional and sovereign wealth attendance.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 13,
    name: "Milken Institute Global Conference",
    startDate: "2026-05-03",
    endDate: "2026-05-06",
    location: "Beverly Hills, CA",
    region: "North America",
    attendance: 4000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Policy/Regulatory", "C-Suite Executives", "Philanthropists"],
    url: "https://milkeninstitute.org/events",
    notes: "Premier gathering of global capital allocators and policymakers. Digital assets increasingly featured. Critical for understanding macro institutional thinking.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 14,
    name: "Consensus Miami (CoinDesk)",
    startDate: "2026-05-05",
    endDate: "2026-05-07",
    location: "Miami, FL",
    region: "North America",
    attendance: 20000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Founders/Builders", "VCs", "Exchanges", "Media"],
    url: "https://consensus.coindesk.com",
    notes: "Crypto's longest-running and most influential conference. Miami debut. Strong institutional track. Major announcements expected.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 15,
    name: "SALT Conference",
    startDate: "2026-05-11",
    endDate: "2026-05-14",
    location: "New York, NY",
    region: "North America",
    attendance: 2000,
    category: "institutional",
    tier: 2,
    estimated: false,
    audience: ["Hedge Funds", "Institutional Investors", "Family Offices", "Allocators"],
    url: "https://www.saltconference.com",
    notes: "SkyBridge Capital's hedge fund and alternatives conference. Digital assets increasingly featured. Strong allocator presence.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 16,
    name: "Sohn Investment Conference",
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    location: "New York, NY",
    region: "North America",
    attendance: 1500,
    category: "institutional",
    tier: 2,
    estimated: false,
    audience: ["Hedge Funds", "Institutional Investors", "Asset Managers"],
    url: "https://sohnconference.org",
    notes: "Elite investment ideas conference. Top hedge fund managers present their best long/short ideas. Crypto increasingly featured.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 17,
    name: "Money20/20 Europe",
    startDate: "2026-06-02",
    endDate: "2026-06-04",
    location: "Amsterdam, Netherlands",
    region: "Europe",
    attendance: 7000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Fintech Founders", "Banks", "Payment Processors"],
    url: "https://europe.money2020.com",
    notes: "Europe's largest fintech and payments event. Strong crypto/digital assets track. Critical for understanding payments infrastructure evolution.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 18,
    name: "SuperReturn International",
    startDate: "2026-06-08",
    endDate: "2026-06-12",
    location: "Berlin, Germany",
    region: "Europe",
    attendance: 3000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Private Equity", "Institutional Investors", "LPs", "Fund Managers"],
    url: "https://informaconnect.com/superreturn-international",
    notes: "Private equity industry's premier conference. Digital asset fund managers increasingly present. Critical for LP relationships.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 19,
    name: "Point Zero Forum",
    startDate: "2026-06-23",
    endDate: "2026-06-25",
    location: "Zurich, Switzerland",
    region: "Europe",
    attendance: 2000,
    category: "crossover",
    tier: 2,
    estimated: false,
    audience: ["Central Bankers", "Regulators", "Institutional Investors", "Technologists"],
    url: "https://www.pointzeroforum.com",
    notes: "Leading central bankers, regulators, and industry leaders discuss digital finance and blockchain. Strong policy focus. CBDC-heavy.",
    digitalAssetRelevance: "Yes"
  },

  // === 2026 Q3 EVENTS ===
  {
    id: 20,
    name: "Korea Blockchain Week",
    startDate: "2026-09-29",
    endDate: "2026-10-01",
    location: "Seoul, South Korea",
    region: "Asia",
    attendance: 10000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Founders/Builders", "Institutional Investors", "VCs", "Exchanges"],
    url: "https://koreablockchainweek.com",
    notes: "Asia's largest blockchain festival. Upbit as main sponsor. Critical for Asian market insights and capital. Strong DeFi and gaming focus.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 21,
    name: "TOKEN2049 Singapore",
    startDate: "2026-10-07",
    endDate: "2026-10-08",
    location: "Singapore",
    region: "Asia",
    attendance: 10000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Founders/Builders", "VCs", "Exchanges"],
    url: "https://token2049.com",
    notes: "Asia's premier crypto event. Gateway to Asian institutional capital. Strong government and sovereign wealth presence.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 22,
    name: "Permissionless (Blockworks)",
    startDate: "2026-10-06",
    endDate: "2026-10-08",
    location: "Salt Lake City, UT",
    region: "North America",
    attendance: 5000,
    category: "crypto",
    tier: 2,
    estimated: true,
    audience: ["Crypto Natives", "Founders/Builders", "VCs", "Traders"],
    url: "https://blockworks.co/event/permissionless",
    notes: "Blockworks' crypto-native event. DeFi and onchain finance focus. More technical than DAS. Strong founder and builder community.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 23,
    name: "Money20/20 USA",
    startDate: "2026-10-18",
    endDate: "2026-10-21",
    location: "Las Vegas, NV",
    region: "North America",
    attendance: 12000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Fintech Founders", "Banks", "Payment Processors"],
    url: "https://us.money2020.com",
    notes: "Fintech's #1 event. 1 in 3 C-suite leaders attend. Strong digital assets presence. Critical for payments and fintech infrastructure insights.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 36,
    name: "Digital Asset Summit London (Blockworks)",
    startDate: "2026-10-20",
    endDate: "2026-10-21",
    location: "London, UK",
    region: "Europe",
    attendance: 2000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Crypto Natives", "Hedge Funds", "Asset Managers"],
    url: "https://blockworks.co",
    notes: "Blockworks' European flagship. Bridges TradFi and crypto for European institutional market. Strong allocator and asset manager attendance.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 24,
    name: "Hong Kong FinTech Week",
    startDate: "2026-11-02",
    endDate: "2026-11-06",
    location: "Hong Kong",
    region: "Asia",
    attendance: 30000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Fintech Founders", "Government", "Banks"],
    url: "https://www.fintechweek.hk",
    notes: "Asia's largest fintech festival. Strong government backing. Digital assets and blockchain prominently featured. Critical for Asian fintech landscape.",
    digitalAssetRelevance: "Yes"
  },

  // === 2026 Q4 EVENTS ===
  {
    id: 25,
    name: "Devcon (Ethereum)",
    startDate: "2026-11-03",
    endDate: "2026-11-06",
    location: "Mumbai, India",
    region: "Asia",
    attendance: 5000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Developers", "Researchers", "Core Contributors", "Academics"],
    url: "https://devcon.org",
    notes: "Ethereum Foundation's annual developer conference. Most technical Ethereum event. Core protocol discussions. India debut opens South Asian market.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 26,
    name: "Abu Dhabi Finance Week (ADFW)",
    startDate: "2026-12-07",
    endDate: "2026-12-11",
    location: "Abu Dhabi, UAE",
    region: "Middle East",
    attendance: 12000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Sovereign Wealth", "Banks", "Asset Managers"],
    url: "https://adfw.ae",
    notes: "Middle East's premier financial event. Strong crypto and digital assets presence. ADGM Hub71 ecosystem. Critical for sovereign wealth access.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 37,
    name: "Digital Asset Summit UAE (Blockworks)",
    startDate: "2026-12-09",
    endDate: "2026-12-10",
    location: "Abu Dhabi, UAE",
    region: "Middle East",
    attendance: 1500,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Crypto Natives", "Sovereign Wealth", "Asset Managers"],
    url: "https://blockworks.co",
    notes: "Blockworks' Middle East expansion. Timed alongside ADFW to capture sovereign wealth and regional institutional interest. Focus on digital assets and tokenization.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 27,
    name: "Solana Breakpoint",
    startDate: "2026-11-15",
    endDate: "2026-11-17",
    location: "London, UK",
    region: "Europe",
    attendance: 8000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Founders/Builders", "Developers", "VCs", "Institutional Investors"],
    url: "https://solana.com/breakpoint",
    notes: "Solana's annual flagship conference. London debut. Strong institutional focus given Solana's institutional traction. Olympia Convention Centre.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 28,
    name: "Singapore FinTech Festival",
    startDate: "2026-11-18",
    endDate: "2026-11-20",
    location: "Singapore",
    region: "Asia",
    attendance: 70000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Fintech Founders", "Government", "Banks"],
    url: "https://www.fintechfestival.sg",
    notes: "World's largest fintech festival. MAS and SFA backed. Massive attendance. Digital assets and blockchain prominently featured. SFF x SFF Awards.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 29,
    name: "Web Summit",
    startDate: "2026-11-02",
    endDate: "2026-11-05",
    location: "Lisbon, Portugal",
    region: "Europe",
    attendance: 70000,
    category: "institutional",
    tier: 2,
    estimated: false,
    audience: ["Tech Founders", "VCs", "Institutional Investors", "Media"],
    url: "https://websummit.com",
    notes: "Europe's largest tech conference. Crypto/blockchain increasingly featured. Massive attendance but broad focus beyond digital assets.",
    digitalAssetRelevance: "Emerging"
  },

  // === 2027 EVENTS ===
  {
    id: 30,
    name: "World Economic Forum (Davos)",
    startDate: "2027-01-18",
    endDate: "2027-01-22",
    location: "Davos, Switzerland",
    region: "Europe",
    attendance: 3000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Policy/Regulatory", "Institutional Investors", "C-Suite Executives"],
    url: "https://www.weforum.org",
    notes: "2027 edition. Digital currency and blockchain track expanding. Critical for policy insights.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 31,
    name: "iConnections Global Alts",
    startDate: "2027-02-22",
    endDate: "2027-02-25",
    location: "Miami Beach, FL",
    region: "North America",
    attendance: 5000,
    category: "institutional",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Hedge Funds", "Allocators", "Family Offices"],
    url: "https://iconnections.io",
    notes: "2027 edition. Crypto managers increasingly represented.",
    digitalAssetRelevance: "Emerging"
  },
  {
    id: 32,
    name: "Digital Asset Summit NYC (Blockworks)",
    startDate: "2027-03-23",
    endDate: "2027-03-25",
    location: "New York, NY",
    region: "North America",
    attendance: 3000,
    category: "crossover",
    tier: 1,
    estimated: false,
    audience: ["Institutional Investors", "Crypto Natives", "Hedge Funds", "RWA Issuers"],
    url: "https://blockworks.co",
    notes: "2027 edition. Expected attendance growth. RWA and tokenization focus.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 33,
    name: "EthCC (Ethereum Community Conference)",
    startDate: "2027-04-05",
    endDate: "2027-04-08",
    location: "Cannes, France",
    region: "Europe",
    attendance: 5000,
    category: "crypto",
    tier: 1,
    estimated: false,
    audience: ["Founders/Builders", "Developers", "Researchers", "VCs"],
    url: "https://ethcc.io",
    notes: "EthCC[10]. Confirmed through 2028 in Cannes.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 34,
    name: "Consensus",
    startDate: "2027-06-09",
    endDate: "2027-06-11",
    location: "Toronto, Canada",
    region: "North America",
    attendance: 16000,
    category: "crypto",
    tier: 1,
    estimated: true,
    audience: ["Institutional Investors", "Founders/Builders", "VCs", "Exchanges"],
    url: "https://consensus.coindesk.com",
    notes: "2027 edition. Location estimated based on CoinDesk rotation patterns.",
    digitalAssetRelevance: "Yes"
  },
  {
    id: 35,
    name: "Bitcoin Miami",
    startDate: "2027-05-24",
    endDate: "2027-05-26",
    location: "Miami, FL",
    region: "North America",
    attendance: 30000,
    category: "crypto",
    tier: 1,
    estimated: true,
    audience: ["Bitcoin Maximalists", "Institutional Investors", "Miners", "Policy"],
    url: "https://b.tc/conference",
    notes: "2027 edition. Expected continued growth.",
    digitalAssetRelevance: "Yes"
  }
];

// Additional industry events to watch
const additionalEvents = [
  "Hedgeweek European Summit (Q2, London)",
  "Context Summits (Jan, Miami)",
  "IMN Beneficial Owners' Securities Lending (Q1)",
  "Greenwich Economic Forum (Oct, Greenwich CT)",
  "GAIM Ops Cayman (Mar, Grand Cayman)",
  "Institutional Investor Alpha (various)",
  "Aumni/JPM/GS Digital Asset Forums (various)",
  "WEF Digital Currency Governance events",
  "Proof of Talk Paris (~June)",
  "ETHGlobal hackathons (rolling)",
  "Digital Asset Forum (various)"
];
